### ISSUE TITLE
Train and deploy recording-level classifiers

### ISSUE THREAD

**Issue by tyiannak** [tyiannak/readys#28]

**Comment by sofiaele** [comment]
One slight problem. 
Train_recording_level_classifier.py and test_recording_level.py are using text_analysis and audio_analysis without problem. 
But if we want to run text_analysis or audio_analysis from command line independently, we get an import error.  
More specifically text_analysis imports models.test_text and test_text imports feature_extraction which is in the same directory as test_text (models directory) but text_analysis cannot recognize it. 
If we replace ' import feature_extraction' (in test_text) with ' import .feature_extraction' , the problem is gone but then this new import occurs error when running test_recording_level.py (vice versa)

**Comment by tyiannak** [comment]
keep getting this error, probably related to invalid components in PCA

`/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/imblearn/pipeline.py", line 277, in fit
    Xt, yt, fit_params = self._fit(X, y, **fit_params)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/imblearn/pipeline.py", line 233, in _fit
    **fit_params_steps[name]
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/joblib/memory.py", line 565, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/joblib/memory.py", line 531, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/joblib/memory.py", line 727, in call
    output = self.func(*args, **kwargs)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sklearn/pipeline.py", line 754, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sklearn/decomposition/_pca.py", line 376, in fit_transform
    U, S, Vt = self._fit(X)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sklearn/decomposition/_pca.py", line 423, in _fit
    return self._fit_full(X, n_components)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/sklearn/decomposition/_pca.py", line 436, in _fit_full
    raise ValueError("n_components='mle' is only supported "
ValueError: n_components='mle' is only supported if n_samples >= n_features
`
